engines:
  # ... CONFIG CONTENT ...
  markdownlint:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      MD013:
        enabled: false
      MD009:
        enabled: false
# ... CONFIG CONTENT ...