version: '2'

services:
  jupyter:
    build:
      context: ./jupyter-docker
      dockerfile: ./jupyter.Dockerfile
    ports:
      - 8888:8888
  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --oplogSize 128
