version: '2'

services:
  jupyter:
    build:
      context: ./jupyter-docker
      dockerfile: ./jupyter.Dockerfile
    ports:
      - 8888:8888
    depends_on:
      - rocketchat

  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --oplogSize 128

  rocketchat:
    image: rocket.chat:latest
    restart: unless-stopped
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - ADMIN_USERNAME=admin
      - ADMIN_PASS=admin
    ports:
      - 3000:3000
    depends_on:
      - mongo

  actions:
    build:
      context: ./bot/actions
      dockerfile: ./docker/actions.Dockerfile
    ports:
      - 5055:5055
    volumes:
      - ./bot/actions:/bot/actions
      - ./bot/Makefile:/bot/Makefile
    # command: "make run-actions"

  bot:
    build:
      context: .
      dockerfile: ./docker/bot.Dockerfile
    restart: unless-stopped
    environment:
      - MAX_TYPING_TIME=8
      - MIN_TYPING_TIME=1
      - WORDS_PER_SECOND_TYPING=10
      - ROCKETCHAT_URL=rocketchat:3000
      - ROCKETCHAT_ADMIN_USERNAME=admin
      - ROCKETCHAT_ADMIN_PASSWORD=admin
      - ROCKETCHAT_BOT_USERNAME=bot
      - ROCKETCHAT_BOT_PASSWORD=bot
      - ROCKETCHAT_BOT_EMAIL=equipebot19_UNB@gmail.com

      # Should be set to 'production' or 'beta' or 'dev'
      # - ENVIRONMENT_NAME=${ENV_NAME}
      - ENVIRONMENT_NAME='dev'
      # Last commit hash using this command: git rev-parse HEAD
      - BOT_VERSION=0.1.0-alpha

      # Analytics config
      - ENABLE_ANALYTICS=False
      - ELASTICSEARCH_URL=elasticsearch:9200

      # # HTTP login on elasticsearch
      # - ELASTICSEARCH_USER=admin
      # - ELASTICSEARCH_PASSWORD=admin
      # - ELASTICSEARCH_HTTP_SCHEME=https
      # - ELASTICSEARCH_PORT=443

    ports:
      - 5005:5005
      - 5002:5002
    depends_on:
      - actions
      - rocketchat
    volumes:
      - ./bot:/bot
      - ./scripts:/scripts
