apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: jupyter
  name: jupyter
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: jupyter
    spec:
      containers:
      - image: gabrielziegler/pylearner-jupyter
        name: jupyter
        ports:
        - containerPort: 8888
        resources: {}
      restartPolicy: Always
status: {}
