apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: rocketchat
  name: rocketchat
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rocketchat
    spec:
      containers:
      - args:
        - bash
        - -c
        - for i in `seq 1 30`; do node main.js && s=$? && break || s=$?; echo "Tried
          $i times. Waiting 5 secs..."; sleep 5; done; (exit $s)
        env:
        - name: ADMIN_PASS
          value: XSjp4iTA7tZJDe9FR
        - name: ADMIN_USERNAME
          value: pyteradmin
        - name: ENVIRONMENT_NAME
          value: '''dev'''
        - name: MONGO_OPLOG_URL
          value: mongodb://mongo:27017/local
        - name: MONGO_URL
          value: mongodb://mongo:27017/rocketchat
        - name: NUM_EPOCHS
          value: "4"
        - name: PORT
          value: "3000"
        - name: ROCKETCHAT_ADMIN_EMAIL
          value: gabrielziegler3@gmail.com
        - name: ROCKETCHAT_ADMIN_PASSWORD
          value: XSjp4iTA7tZJDe9FR
        - name: ROCKETCHAT_ADMIN_USERNAME
          value: pyteradmin
        - name: ROCKETCHAT_BOT_EMAIL
          value: pyterthebot@gmail.com
        - name: ROCKETCHAT_BOT_PASSWORD
          value: MuCzLrDzFEhun97JX
        - name: ROCKETCHAT_BOT_USERNAME
          value: PyterTheBot
        - name: ROCKETCHAT_URL
          value: rocketchat:3000
        - name: ROOT_URL
          value: http://localhost:3000
        image: rocket.chat:latest
        name: rocketchat
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
